spring:
  cloud:
    gateway:
      routes:
#      测试
      - id: Bing
        uri: https://bing.com
        predicates:
        - Query=uri, bing
      - id: rkyang
        uri: http://rkyang.cn
        predicates:
        - Query=uri, rky\

#      商品服务网关
      - id: product_route
        uri: lb://gulimall-product
        predicates:
          - Path=/api/product/**
        filters:
          - RewritePath=/api/(?<segment>.*),/$\{segment}

#      会员服务网关
      - id: member_route
        uri: lb://gulimall-member
        predicates:
          - Path=/api/member/**
        filters:
          - RewritePath=/api/(?<segment>.*),/$\{segment}

#      仓库服务网关
      - id: ware_route
        uri: lb://gulimall-ware
        predicates:
          - Path=/api/ware/**
        filters:
          - RewritePath=/api/(?<segment>.*),/$\{segment}

#       第三方服务网关
      - id: third_party_route
        uri: lb://gulimall-third-party
        predicates:
          - Path=/api/third-party/**
        filters:
          - RewritePath=/api/third-party/(?<segment>.*),/$\{segment}

#      主系统网关，默认请求renren-fast
      - id: admin_route
#        lb:表示负载均衡
        uri: lb://renren-fast
        predicates:
#          匹配地址
          - Path=/api/**
        filters:
#          重写请求地址
          - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

#     nginx代理网关
      - id: nginx_route
        uri: lb://gulimall-product
        predicates:
            #          匹配host
          - Host=**.guli.com
    nacos:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-gateway
server:
  port: 88